name: internappflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.1
  http: ^1.5.0
  firebase_analytics: ^12.0.0
  cloud_firestore: ^6.0.0
  flutter_svg: ^2.0.10+1
  file_picker: ^10.3.3
  dotted_border: ^3.1.0
  flutter_card_swiper: ^7.0.1
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1
  swipe_cards: ^2.0.0+1
  provider: ^6.1.5+1
  firebase_storage: ^13.0.2
  url_launcher: ^6.3.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  appinio_swiper: ^2.1.1
  image_picker: ^1.0.7
  lottie: ^3.3.1
  video_player: ^2.10.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/hyrup/splash_logo.json
    - assets/animations/empty/empty_lottie.json
    - assets/animations/searching/searching_lottie.json
    - assets/animations/error/error_lottie.json
    - assets/animations/coming_soon/coming_soon_lottie.json
    - assets/bear.gif
    - assets/Union.svg
    - assets/svg/logo.svg
    - assets/svg/logo_text.svg
    - assets/svg/google_logo.svg
    - assets/images/Cartoon_Network_Bear_Sticker.png
    - assets/svg/Group_bottom.svg
    - assets/images/Group_bottom.png
    - assets/idBackground.png
    - assets/placeholder.png
    - assets/addItem.png
    - assets/Button.png
    - assets/images/UI.png
    - assets/images/Lumel_Logo.png
    - assets/puzzle.png
    - assets/images/girl.png
    - assets/images/2image1.png
    - assets/images/2text2.png
    - assets/images/2text1.png
    - assets/images/JUMP.png
    - assets/images/IN.png
    - assets/images/Star2.png
    - assets/images/YOUR.png
    - assets/images/DREAMS.png
    - assets/images/TO.png
    - assets/images/union1.png
    - assets/images/cwg.png
    - assets/images/arrow_outward.png
    - assets/images/google.png
    - assets/outreach.png
    - assets/inhouse.png
    - assets/campus.png
    - assets/Union.png
    - assets/images/puzzle.png
    - assets/text.png
    - assets/skills.json
    - assets/animations/Stressed Woman at work.json
    - assets/animations/Trophy animation.json
    - assets/jobPeference.json
    - assets/userskills.json
    - assets/images/job_card/banner_background.png

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/jost/Jost-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/hyrup.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/hyrup.png"
   